services:
  - type: worker
    name: buylow-telegram-bot
    env: python
    runtime: python-3.11
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHECK_INTERVAL
        value: 900
