services:
  - type: worker
    name: buylow-telegram-bot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHECK_INTERVAL
        value: 900
